#!/bin/sh
#********************************************************************************
# Check values of some conf-* files
#

# check if '*qmail' is installed
echo -n "Checking for 'qmail' home ..."
ls `head -1 conf-qmail` >>/dev/null 2>&1
if [ $? -ne 0 ] ; then
  echo -e "\e[37;1m"
  echo    "Couldn't find your \"qmail\" home directory. Either there is nothing"
  echo -e "installed or the path in \"conf-qmail\" is wrong. \e[31;1mAborting!"
  echo -e "\e[0m"
  exit 1
 else
  echo " found "`head -1 conf-qmail`"!"
fi

# check user/group against 'conf-usrgrp'
echo -n "Checking for 'qmail' users and groups ..."
UG=$(head -1 conf-usrgrp)
U=$(echo $UG | cut -d. -f1)
G=$(echo $UG | cut -d. -f2)

id -u $U >>/dev/null 2>&1
if [ $? -ne 0 ] ; then
  echo -e "\e[37;1m"
  echo -e "User id error! The qmail daemon user couldn't be found! \e[31;1mAborting!"
  echo -e "\e[0m"
  exit 1
fi 

T=$(id -nG $U) >>/dev/null 2>&1
if [ $G != $T ] ; then
  echo -e "\e[37;1m"
  echo -e "Group id error! The group \"$G\" from \"conf-usrgrp\" isn't correct! \e[31;1mAborting!"
  echo -e "\e[0m"
  exit 1
fi
echo " found!"
